import { Button } from "@/components/ui/button";
import UserHero from "@/components/user/UserHero";
import React from "react";
import VisiMisi from "./_components/Visimisi";
import Profile from "./_components/Profile";
import { getCurrentUser } from "@/services/user";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Si Input",
  description: "Generated by si Input",
};

const UserPage = async () => {
  return (
    <>
      <div className="space-y-8">
        <UserHero />
        <Profile />
        <VisiMisi />
      </div>
    </>
  );
};

export default UserPage;
